language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-9.1.14.0
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-9.0.5.0
gemfile: .travis.gemfile
script: bundle exec rake spec_travis spec_sqlite
before_script:
  - mysql -e 'create database rodauth_test;'
  - psql -c 'create database rodauth_test;' -U postgres
addons:
  postgresql: "9.6"
services:
  - postgresql
